FROM apache/airflow:2.7.2-python3.8

USER root

# Instalar Java 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean

# Definir JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

# Cambiar a usuario airflow antes de instalar paquetes Python
USER airflow

# Instalar PySpark como usuario airflow
RUN pip install pyspark

